# The version of this configuration format
version: 1

# The name and version of the FHIR Package, as found on simplifier.net
package:
  name: hl7.fhir.r4.core
  version: "4.0.1"

# The output transformations of the parsed FHIR content
transformations:
  - input:
      type: StructureDefinition
      if: '{{ eq .Kind "primitive-type" }}'
    output: '{{ .Package | replace "." "/" | cutprefix "hl7/fhir/" }}/{{ .Name | snakecase }}.go'
    template: '.fhenix/r4/templates/primitive.go.tmpl'
  - input:
      type: StructureDefinition
      if: '{{ and (eq .Kind "complex-type") .IsSpecialization }}'
    output: '{{ .Package | replace "." "/" | cutprefix "hl7/fhir/" }}/{{ .Name | snakecase }}.go'
    template: '.fhenix/r4/templates/complex.go.tmpl'
  - input:
      type: StructureDefinition
      if: '{{ or (eq .Name "StructureDefinition") (eq .Name "ElementDefinition") }}'
    output: '{{ .Package | replace "." "/" | cutprefix "hl7/fhir/" }}/resources/{{ .Name | lowercase }}/{{ .Name | snakecase }}.go'
    template: '.fhenix/r4/templates/resource.go.tmpl'

  # Define root interfaces in the 'core' package, so that they can be used by
  # element definitions.
  - input:
      type: StructureDefinition
      if: '{{ .IsAbstract }}'
    output: '{{ .Package | replace "." "/" | cutprefix "hl7/fhir/" }}/{{ .Name | snakecase }}.go'
    template: '.fhenix/r4/templates/base-profile.go.tmpl'

  - input:
      type: StructureDefinition
      if: '{{ or .IsAbstract .HasDerived }}'
    output: '{{ .Package | replace "." "/" | cutprefix "hl7/fhir/" }}/internal/profileimpl/{{ .Name | snakecase }}.go'
    template: '.fhenix/r4/templates/profileimpl.go.tmpl'
