// GENERATE CODE - DO NOT EDIT
//
// This file is generated by the FHIR Fhenix code generator tool, which can be
// located at https://github.com/friendly-fhir/fhenix.

package fhir

import (
	"github.com/friendly-fhir/go-fhir/r4/core/internal/profileimpl"

	"encoding/json"
)

// Base StructureDefinition for unsignedInt type: An integer with a value that
// is not negative (e.g. >= 0)
//
// Meta Details:
//
//   - Package IG: hl7.fhir.r4.core@4.0.1
//   - StructureDefinition: http://hl7.org/fhir/StructureDefinition/unsignedInt
//   - Source File: StructureDefinition-unsignedInt.json
type UnsignedInt struct {

	// May be used to represent additional information that is not part of the
	// basic definition of the resource. To make the use of extensions safe and
	// manageable, there is a strict set of governance applied to the definition
	// and use of extensions. Though any implementer can define an extension, there
	// is a set of requirements that SHALL be met as part of the definition of the
	// extension.
	Extension []*Extension `fhirpath:"extension"`

	// unique id for the element within a resource (for internal references)
	ID string `fhirpath:"id"`

	// Primitive value for unsignedInt
	Value uint32 `fhirpath:"value"`

	profileimpl.BaseInteger
	profileimpl.BaseElement
}

// GetExtension returns the value of the field Extension.
// This function is safe to call on nil pointers, and will return the zero value
// instead.
func (ui *UnsignedInt) GetExtension() []*Extension {
	if ui == nil {
		return nil
	}
	return ui.Extension
}

// GetID returns the value of the field ID.
// This function is safe to call on nil pointers, and will return the zero value
// instead.
func (ui *UnsignedInt) GetID() string {
	if ui == nil {
		return ""
	}
	return ui.ID
}

// GetValue returns the value of the field Value.
// This function is safe to call on nil pointers, and will return the zero value
// instead.
func (ui *UnsignedInt) GetValue() uint32 {
	if ui == nil {
		return 0
	}
	return ui.Value
}

func (ui *UnsignedInt) MarshalJSON() ([]byte, error) {
	return json.Marshal(ui.Value)
}

func (ui *UnsignedInt) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &ui.Value)
}

var _ json.Marshaler = (*UnsignedInt)(nil)
var _ json.Unmarshaler = (*UnsignedInt)(nil)
