// GENERATE CODE - DO NOT EDIT
//
// This file is generated by the FHIR Fhenix code generator tool, which can be
// located at https://github.com/friendly-fhir/fhenix.

package fhir

import (
	"github.com/friendly-fhir/go-fhir/r4/core/internal/profileimpl"

	"encoding/json"
)

// Base StructureDefinition for xhtml Type
//
// Meta Details:
//
//   - Package IG: hl7.fhir.r4.core@4.0.1
//   - StructureDefinition: http://hl7.org/fhir/StructureDefinition/xhtml
//   - Source File: StructureDefinition-xhtml.json
type XHTML struct {

	// unique id for the element within a resource (for internal references)
	ID string `fhirpath:"id"`

	// Actual xhtml
	Value string `fhirpath:"value"`

	profileimpl.BaseElement
}

// GetExtension returns the value of the field Extension.
// This function is safe to call on nil pointers, and will return the zero value
// instead.
func (x *XHTML) GetExtension() *Extension {
	return nil
}

// GetID returns the value of the field ID.
// This function is safe to call on nil pointers, and will return the zero value
// instead.
func (x *XHTML) GetID() string {
	if x == nil {
		return ""
	}
	return x.ID
}

// GetValue returns the value of the field Value.
// This function is safe to call on nil pointers, and will return the zero value
// instead.
func (x *XHTML) GetValue() string {
	if x == nil {
		return ""
	}
	return x.Value
}

func (x *XHTML) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.Value)
}

func (x *XHTML) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

var _ json.Marshaler = (*XHTML)(nil)
var _ json.Unmarshaler = (*XHTML)(nil)
