// GENERATE CODE - DO NOT EDIT
//
// This file is generated by the FHIR Fhenix code generator tool, which can be
// located at https://github.com/friendly-fhir/fhenix.
package fhir

import (
	"github.com/friendly-fhir/go-fhir/r4/core/internal/profileimpl"
)

// Base StructureDefinition for xhtml Type
//
// Meta Details:
//
//   - Package IG: hl7.fhir.r4.core@4.0.1
//   - StructureDefinition: http://hl7.org/fhir/StructureDefinition/xhtml
//   - Source File: StructureDefinition-xhtml.json
type Xhtml struct {

	// unique id for the element within a resource (for internal references)
	Id string `json:"id"`

	// Actual xhtml
	Value string `json:"value"`

	profileimpl.BaseElement
}

func (x *Xhtml) GetExtension() []*Extension {
	return nil
}

func (x *Xhtml) GetId() string {
	if x == nil {
		return ""
	}
	return x.Id
}

func (x *Xhtml) GetValue() string {
	if x == nil {
		return ""
	}
	return x.Value
}

var _ Element = (*Xhtml)(nil)
